version: 0.0
os: linux
files:
  - source: hello-service-1.0-SNAPSHOT.jar
    destination: /home/ec2-user
hooks:
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: ec2-user
