version: 0.0
os: linux
files:
  - source: hello-service-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/app.jar
  - source: application_start.sh
    destination: /home/ec2-user/application_start.sh
hooks:
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: ec2-user
